// Target metadata checked against TcpQuality c2295ae096437859ce4bbc36f170428fcac47be9 (2026-09-30).
// Domains and paths are public target facts; measurement code remains Aster's.
const WEBSITE_CATALOG = [
  {
    name: "Adobe Assets",
    host: "assets.adobe.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Amazon",
    host: "www.amazon.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Apple iCloud",
    host: "www.icloud.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "AWS STS",
    host: "sts.amazonaws.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "ChatGPT",
    host: "chatgpt.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Claude",
    host: "claude.ai",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Cloudflare Dashboard",
    host: "dash.cloudflare.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Discord Gateway",
    host: "gateway.discord.gg",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Dropbox API",
    host: "api.dropboxapi.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Facebook",
    host: "www.facebook.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "GitHub API",
    host: "api.github.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "GitLab",
    host: "gitlab.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Gmail",
    host: "mail.google.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Google Search",
    host: "www.google.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Google Static",
    host: "www.gstatic.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Instagram",
    host: "www.instagram.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Microsoft Login",
    host: "login.microsoftonline.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Netflix API",
    host: "api-global.netflix.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "NodeSeek",
    host: "www.nodeseek.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Notion API",
    host: "api.notion.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "OpenAI API",
    host: "api.openai.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "PayPal API",
    host: "api-m.paypal.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Reddit OAuth",
    host: "oauth.reddit.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Slack App",
    host: "app.slack.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Spotify Web",
    host: "open.spotify.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Steam",
    host: "store.steampowered.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Telegram",
    host: "telegram.org",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Wikipedia",
    host: "www.wikipedia.org",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "X",
    host: "x.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "YouTube API",
    host: "youtubei.googleapis.com",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Zoom API",
    host: "api.zoom.us",
    group: "网站 / API",
    provider: "Website",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Akamai Edge",
    host: "www.akamai.com",
    group: "静态资源 CDN",
    provider: "Akamai",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "AWS CloudFront",
    host: "d1.awsstatic.com",
    group: "静态资源 CDN",
    provider: "CloudFront",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "CacheFly",
    host: "cachefly.cachefly.net",
    group: "静态资源 CDN",
    provider: "CacheFly",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Cloudflare CDNJS",
    host: "cdnjs.cloudflare.com",
    group: "静态资源 CDN",
    provider: "Cloudflare",
    path: "/ajax/libs/jquery/3.7.1/jquery.min.js",
    reference: "TcpQuality",
  },
  {
    name: "Fastly Test",
    host: "http-me.fastly.dev",
    group: "静态资源 CDN",
    provider: "Fastly",
    path: "/",
    reference: "TcpQuality",
  },
  {
    name: "Google Hosted Libraries",
    host: "ajax.googleapis.com",
    group: "静态资源 CDN",
    provider: "Google",
    path: "/ajax/libs/jquery/3.7.1/jquery.min.js",
    reference: "TcpQuality",
  },
  {
    name: "jsDelivr Multi-CDN",
    host: "cdn.jsdelivr.net",
    group: "静态资源 CDN",
    provider: "jsDelivr",
    path: "/npm/jquery@3.7.1/dist/jquery.min.js",
    reference: "TcpQuality",
  },
  {
    name: "UNPKG Cloudflare",
    host: "unpkg.com",
    group: "静态资源 CDN",
    provider: "UNPKG",
    path: "/jquery@3.7.1/dist/jquery.min.js",
    reference: "TcpQuality",
  },
  {
    name: "www.youtube.com",
    host: "www.youtube.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "github.com",
    host: "github.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.cloudflare.com",
    host: "www.cloudflare.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.microsoft.com",
    host: "www.microsoft.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.apple.com",
    host: "www.apple.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.netflix.com",
    host: "www.netflix.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.reddit.com",
    host: "www.reddit.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.openai.com",
    host: "www.openai.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
  {
    name: "www.bing.com",
    host: "www.bing.com",
    group: "常用首页",
    provider: "Website",
    path: "/",
    reference: "Aster",
  },
];
const RECOMMENDED = [
  "www.google.com",
  "www.youtube.com",
  "github.com",
  "www.cloudflare.com",
  "www.wikipedia.org",
  "www.microsoft.com",
];
const WEBSITES = [
  ...new Set([...RECOMMENDED, ...WEBSITE_CATALOG.map((x) => x.host)]),
];
module.exports = { WEBSITE_CATALOG, WEBSITES, RECOMMENDED };
